### ISSUE TITLE
make-xges error

### ISSUE THREAD

**Issue by r4pt0r66** [plugorgau/bbb-render#12]
I'm getting the following error with make-xges:

```
Traceback (most recent call last):
  File "./make-xges.py", line 428, in <module>
    sys.exit(main(sys.argv))
  File "./make-xges.py", line 423, in main
    p = Presentation(opts)
  File "./make-xges.py", line 52, in __init__
    self.add_slides(self.opts.annotations)
  File "./make-xges.py", line 201, in add_slides
    asset = self._get_asset(os.path.join(self.opts.basedir, path))
  File "./make-xges.py", line 64, in _get_asset
    asset = GES.UriClipAsset.request_sync(file_to_uri(path))
GLib.Error: gst-resource-error-quark: Resource not found. (3)
```
I've implemented the fix described in [issue-741507162](https://github.com/plugorgau/bbb-render/issues/2#issue-741507162); the presentation doesn't inlude deskshare.webm.

Output of download.py when downloading /deskshare/deskshare.webm is now: HTTPError: 404. In my outdir deskshare.webm is 0 bytes.

**Comment by r4pt0r66** [comment]
Turns out somelines in my copy of `download.py` were malformed; have no idea how that happened:

`        for imgurl in {img.get('{http:# www.w3.org/1999/xlink}href')
                       for img in doc.iterfind('.# {http:# www.w3.org/2000/svg}image')}:`

should've been:
`        for imgurl in {img.get('{http://www.w3.org/1999/xlink}href')
                       for img in doc.iterfind('.//{http://www.w3.org/2000/svg}image')}:`

Then got this error with `make-xges.py`:
`ERROR from element internal-encodebin: Couldn't create encoder for format audio/mpeg, mpegversion=(int)4, base-profile=(string)lc
Debugging info: gstencodebin.c(1171): _post_missing_plugin_message (): /GESPipeline:gespipeline0/GstEncodeBin:internal-encodebin`

Soved with:
`sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav`

Not sure if all of those packages are needed, but it did the trick.
