### ISSUE TITLE
generated xges doesn't render opening credits, pitivi crashes

### ISSUE THREAD

**Issue by jmlich** [plugorgau/bbb-render#17]
It seems some ges-launch-1.0 doesn't render it for some reason:

```
+ ./bbb-render/make-xges.py --start 3667 --end 3677 --backdrop ./output/ne-1-10-00-petr-krcmar-moderni.png --opening-credits /home/jmlich/workspace/openalt2021/bbb-batch-render/output2/ne-1-10-00-petr-krcmar-moderni.png --opening-credits /home/jmlich/workspace/openalt2021/bbb-batch-render/1.png --closing-credits /home/jmlich/workspace/openalt2021/bbb-batch-render/2.png --closing-credits /home/jmlich/workspace/openalt2021/bbb-batch-render/3.png -- /home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659 /home/jmlich/workspace/openalt2021/bbb-batch-render/tmp/ne-1-10-00-petr-krcmar-moderni.xges
+ rm -f /home/jmlich/workspace/openalt2021/bbb-batch-render/video_out/ne-1-10-00-petr-krcmar-moderni.mp4
+ ges-launch-1.0 --load /home/jmlich/workspace/openalt2021/bbb-batch-render/tmp/ne-1-10-00-petr-krcmar-moderni.xges -o /home/jmlich/workspace/openalt2021/bbb-batch-render/video_out/ne-1-10-00-petr-krcmar-moderni.mp4
Loading project from : /home/jmlich/workspace/openalt2021/bbb-batch-render/tmp/ne-1-10-00-petr-krcmar-moderni.xges

Timeline description: `+track video restrictions="video/x-raw(ANY), width=(int)1920, height=(int)1080, framerate=(fraction)30/1" +track audio restrictions="audio/x-raw(ANY), rate=(int)48000, channels=(int)2" +clip file:///home/jmlich/workspace/openalt2021/bbb-batch-render/2.png tt=GES_TRACK_TYPE_VIDEO s=16.000000 d=3.000000 n=uriclip0 set-height 1080 set-width 1920 +clip file:///home/jmlich/workspace/openalt2021/bbb-batch-render/3.png tt=GES_TRACK_TYPE_VIDEO s=19.000000 d=3.000000 n=uriclip1 set-height 1079 set-width 1920 +clip file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/video/webcams.webm layer=1 s=6.000000 inpoint=3667000000000 d=10.000000 n=uriclip2 set-height 270 set-posx 1440 set-width 480 +clip file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/presentation/982c4b42cb1dcbd7d057f2ceff059c81316da45e-1636275148307/slide-1.png tt=GES_TRACK_TYPE_VIDEO layer=2 s=6.000000 d=10.000000 n=uriclip3 set-height 811 set-width 1440 +clip file:///home/jmlich/workspace/openalt2021/bbb-batch-render/output/ne-1-10-00-petr-krcmar-moderni.png tt=GES_TRACK_TYPE_VIDEO layer=4 s=6.000000 d=10.000000 n=uriclip4 set-height 1080 set-width 1920`
====================

  layer 0: 
  --------
    - Clip from: 'file:///home/jmlich/workspace/openalt2021/bbb-batch-render/2.png' [▶PNG]
        start=0:00:16.000000000 duration=0:00:19.000000000
    - Clip from: 'file:///home/jmlich/workspace/openalt2021/bbb-batch-render/3.png' [▶PNG]
        start=0:00:19.000000000 duration=0:00:22.000000000

  layer 1: 
  --------
    - Clip from: 'file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/video/webcams.webm' [∋WebM, ♫Vorbis, ▶VP9]
        start=0:00:06.000000000 inpoint=1:01:07.000000000 duration=0:00:16.000000000

  layer 2: 
  --------
    - Clip from: 'file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/presentation/982c4b42cb1dcbd7d057f2ceff059c81316da45e-1636275148307/slide-1.png' [▶PNG]
        start=0:00:06.000000000 duration=0:00:16.000000000

  layer 4: 
  --------
    - Clip from: 'file:///home/jmlich/workspace/openalt2021/bbb-batch-render/output/ne-1-10-00-petr-krcmar-moderni.png' [▶PNG]
        start=0:00:06.000000000 duration=0:00:16.000000000

<position: 0:00:20.766666665 duration: 0:00:22.000000000/>>
Done

```

The generated xges is here:
```
<ges version='0.7'>
  <project properties='properties;' metadatas='metadatas;'>
    <encoding-profiles>
      <encoding-profile name='MP4' description='bbb-render encoding profile' type='container' format='video/quicktime, variant=(string)iso' >
        <stream-profile parent='MP4' id='0' type='video' presence='0' format='video/x-h264, profile=(string)high' restriction='video/x-raw(ANY), width=(int)1920, height=(int)1080, framerate=(fraction)30/1' pass='0' variableframerate='0' />
        <stream-profile parent='MP4' id='1' type='audio' presence='0' format='audio/mpeg, mpegversion=(int)4, base-profile=(string)lc' restriction='audio/x-raw(ANY), rate=(int)48000, channels=(int)2' />
      </encoding-profile>
    </encoding-profiles>
    <ressources>
      <asset id='file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/deskshare/deskshare.webm' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4, duration=(guint64)28237500000000;' metadatas='metadatas, datetime=(datetime)2021-11-07T18:07:30Z, container-format=(string)Matroska, extended-comment=(string)&quot;MAJOR_BRAND\=isom&quot;, encoder=(string)Lavf58.29.100, file-size=(guint64)56791809;' >
        <stream-info id='3cf741c6cfc0ff2319c4fee3f6b17a98b715291631b801e9d259356f93a4102e/001:001' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='video/x-vp9, width=(int)1280, height=(int)720, framerate=(fraction)30/1, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true, alignment=(string)super-frame, profile=(string)0, codec-alpha=(boolean)false'/>
      </asset>
      <asset id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/output/ne-1-10-00-petr-krcmar-moderni.png' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4;' metadatas='metadatas, file-size=(guint64)51962;' >
        <stream-info id='e92460353623b612050206b00aca29d04ce4057eaf336d4d7241f0439b1a9182' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='image/png, width=(int)1920, height=(int)1080'/>
      </asset>
      <asset id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/1.png' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4;' metadatas='metadatas, file-size=(guint64)250275;' >
        <stream-info id='144f413b48a19503ae52acf033477d1b4af2486154e2db0f8394e8f221c08079' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='image/png, width=(int)1920, height=(int)1080'/>
      </asset>
      <asset id='file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/presentation/982c4b42cb1dcbd7d057f2ceff059c81316da45e-1636275148307/slide-1.png' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4;' metadatas='metadatas, file-size=(guint64)31914;' >
        <stream-info id='333b1cc846c4f3857241ae17740a19efdd8ee912731de0ac89e35c1823bc1e33' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='image/png, width=(int)1600, height=(int)901'/>
      </asset>
      <asset id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/3.png' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4;' metadatas='metadatas, file-size=(guint64)38073;' >
        <stream-info id='8680c97e0700ef8ea47ad2801cbfc559867c9f3fd431c19d48b4ff9a2c6016ae' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='image/png, width=(int)1800, height=(int)1012'/>
      </asset>
      <asset id='file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/video/webcams.webm' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)6, duration=(guint64)28237479000000;' metadatas='metadatas, datetime=(datetime)2021-11-07T17:20:16Z, container-format=(string)Matroska, extended-comment=(string)&quot;MAJOR_BRAND\=isom&quot;, encoder=(string)Lavf58.29.100, file-size=(guint64)782288367;' >
        <stream-info id='dd2f376193d30242478ab455d727d23cdf75bf0979e040ce9711478da9fd54ae/002:002' extractable-type-name='GESAudioUriSource' properties='properties, track-type=(int)2;' metadatas='metadatas;' caps='audio/x-vorbis, channels=(int)2, rate=(int)48000, streamheader=(buffer)&lt; 01766f72626973000000000280bb0000000000000077010000000000b801, 03766f726269730d0000004c61766635382e32392e3130300000000001, 05766f726269732542435601004000002473182a46a5731684101a425019e31c42ce6bec19424c11821c324c5bcb25739021a4a042885b2881d09055000040000087417814848a41082184253d589283273d082184883978148469410821841042082184104208218445396892832741081d84e330380c83e538f81c8445395810832741e820840f42b89a83ac3908218424354850830639e81c84c22c288a82c430b816840435288c82e430c8d4830b42889a834935f81a846741781684694108218424414890830641c8188446415892830639b81484cb41a81a842a39081f842034641500900000a0a2288aa2280a101ab20a00c8000010405114c7711cc9911cc9b11c0b080d590500000100080000a0488aa4488ee44892245992255992255992e689aa2ccbb22ccbb22ccb32101ab20a0048000050510c45711407080d59050064000008a0388aa5588aa5688ae7888e088486ac0200800000040000103443533c479444cf5455d7b66ddbb66ddbb66ddbb66ddbb66d5b966519080d59050040000010d26966a9068830031906424356010008000080118a30c480d09055000040000080184a0ea209ad39df9ce3a0590e9a4ab1391d9c48b579929b8ab939e79c73cec9e69c31ce39e79ca29c590c9a09ad39e79cc4a0590a9a09ad39e79c27b179d09a2aad39e79c71cee9609c11c639e79c26ad79909a8db539e79c05ad698e9a4bb139e79c48b979529b4bb539e79c73ce39e79c73ce39e79ceac5e91c9c13ce39e79ca8bdb9969bd0c539e79c4fc6e9de9c10ce39e79c73ce39e79c73ce39e79c20346415000004004010868d61dc2908d2e768204611621a32e941f7e830091a839c42ead1e868a4943a08259571524a27080d590500000200400821851452482185145248218514628821861872ca29a7a0824a2aa9a8a28c32cb2cb3cc32cb2cb3cc3aecacb30e3b0c31c410432badc452536d35d6586bee39e79a83b4565a6badb5524a29a594520a42435601002000000442061964905148218514628829a79c720a2aa880d090550000200080000000004ff21cd1111dd1111dd1111dd1111dd1f11ccf112551122551122dd33235d35345557565d7967559b77d5bd8855df77dddf77dddf8756158966559966559966559966559966559962034641500000200002084104248218514524829c61873cc39e8249410080d59050000020008000000701447711cc9911c49b2244bd224cdd22c4ff3344f133d511445d33455d1155d51376d513665d3355d53365d55566d57966d5bb675db9765dbf77ddff77ddff77ddff77ddff77d5d0742435601001200003a92232992222992e3388e24494068c82a004006004000008ae2288ee33892244992256992677996a8999ae9999e2aaa4068c82a00001000400000000000008aa6788aa9788aa8788ee88892689996a8a99a2bcaa6ecbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaae0b8486ac02002400007424477224475224455224477280d0905500800c008000001cc3312445722ccbd2344ff3344f133dd1133dd35345577481d0905500002000800000000000000cc9b014cbd11c4d1225d5522d55532dd55245d5535555555555555555555555555555555555555555555555555555555555555555554dd3344d13080d590900900100a0105b4badc5dc096a1c62d272cc24744e6210aab1082247b5b7ca31a51cc59e1a889451127baa28638a49cc31b4d02927add6523a8514a498530a15520e5a2034648500109a01e0701c40b22c40b2340000000000000090340dd03c0fb03c0f00000000000000244d032c4f0334cf030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040d23440f33c40f33c00000000000000d03c0ff04411f04411000000000000002ccf033cd1033c510400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0d13440f33c40f33c00000000000000b03c0ff04411f03c110000000000000034cf033c51043c5104000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000010e00000106021141ab2220088130030380e340d9a06cf03389605cf83e74114018e65c1f3e07910450000000000000000000034cf83aa4255e1aa00cdf360aa5055a82e0000000000000000000096e74155a1aa705d80e5793055982a5415000000000000000000004f14a1ba505db82ac03345b82a5c15aa0b00000000000000000000000000000000000000000000080000187000000830a10c141ab2220088130070388a65010080e338960500008ee3581600005896258a000060599a280200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000187000000830a10c141ab2120088020030288a6501cbb22c6059960534cdb2009606d03c80e7014411000800002870000008b0415362718042435602005100000645b12c4d13459aa6699a268a344dd3344d14799ea6799e6942d33ccf34218a9e679a1045cf334d98a628aa2a10455515000050e00000106083a6c4e2008586ac04004202000c8e62599e278aa2288aa6a9aa344dd33c4f1445d13455d555699aa6799e288aa269aaaaeaf23c4d1345d31445d35455d785a689a2699aa269aaaaebc2f344d1344d535555d575e179a2689aa6a9aaaeebba104551344dd35455d7755d208aa6699aaaeabab20c44d1345555555d579681289aa6aaaaaaebca32304dd35455d7955d590698a6aabaae2ccb3240555dd7756559b601aaeabaae2bcbb20d705dd7956559b66d00ae2bcbb26cdb0200000e1c0000028ca0938c2a8bb0d1840b0f40a1212b0280280000c018a61453ca302621a4101ac624841242262595944aaa20a4525229158454522a25a392526a295510522929950a422aa595540000d8810300d881855068c84a00200f0080204629c618630c32a61463ce390795528a31e79c938c31c69873ce49291963cc39e7a4948c39e79c73524ae69c73ce3929a573ce39e79c94524ae79c734e4a292584ce3927a594d239e79c13000054e000001060a3c8e60423418586ac04005201000c8e63599aa6699e278a9624699ae7799e289aa666499ae6799e278aa6c9f33c4f1445d1345595e7799e288aa269aa2ad71545d3344d555555b22c8aa6699aaaeaba304dd35455d7756598a669aaaaebba2e6cdb5455d5756519b6ad9aaa2abbb20c5c577565d7b681ebbaaeecdab60000f0040700a0021b564738291a0b2c346425009001004018838c4208218510420a2184945208090000187000000830a10c141ab212004805000090b1d65a6badb5d6404729a594524aa9708c524a29a594524a29a594524a29a5944a4a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a05002e553800e83ed8b03ac249d15860a1212b0180540000c018a598724e422915428c392621a5162b8418734e4a4a3116cf3907a194d65a2c9e730e4229adc55854ea9c94945a8aada814322929a5d66210c294945a6ba5b520842aa9c4965a6b41085d536a2996d88210b6b692528c3106e1838fb195586a0c3ef8205b2b31d55a00006683030044820dab239c148d05161ab21200080900208c518a31c61873ce39e724638c31e69c73104208a1648c31e79c730e42082194ce39e79c731042082184524ac79c730e420821845052ea9c73104208a184104a2a9d730e42082184524a49a573104208a18450424925a5d43908218410422929a5944208218412422825a59452082184104228a1a494520a2184524208a59494524a2985104a08a59492524929a5124a09218452524929a51442082594524a2a29a5944a09a184524a29a5a494524a21945042290500001c3800000418412719551661a309171e80424356020064000094b2524a28ad554022a518a4da424799831473892c730c5acda5620e2906ad86ca31a518b416320899524c4a0925754c29272dc5984ae79ca498738da57310000000410080809000000304053300c0e000e17310740204471b00802044668844c3427078500910115301406282422e0054585ca45d5c4097012ee8e2ae0321042108412c0ea080041c9c70c3136f78c20d4ed0292a752000000000000b00f00000905c001111d1cc6164686c7074787c8084888c9008000000000016007c00002425404444347318191a1b1c1d1e1f20212223240100800002000000002080000404040000000000020000000404 &gt;'/>
        <stream-info id='dd2f376193d30242478ab455d727d23cdf75bf0979e040ce9711478da9fd54ae/001:001' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='video/x-vp9, width=(int)1280, height=(int)720, framerate=(fraction)30/1, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true, alignment=(string)super-frame, profile=(string)0, codec-alpha=(boolean)false'/>
      </asset>
      <asset id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/output2/ne-1-10-00-petr-krcmar-moderni.png' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4;' metadatas='metadatas, file-size=(guint64)91292;' >
        <stream-info id='c8c0a2b3aa6d24ca12c5222e335ec3d04b4c088300260dc674ee2533035dd86a' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='image/png, width=(int)1920, height=(int)1080'/>
      </asset>
      <asset id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/2.png' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4;' metadatas='metadatas, file-size=(guint64)107581;' >
        <stream-info id='025b6977a2cce1ee3a63da6e6bd394f2ad28b4ae5db72abcd62aab73f4e26fc0' extractable-type-name='GESVideoUriSource' properties='properties, track-type=(int)4;' metadatas='metadatas;' caps='image/png, width=(int)1920, height=(int)1080'/>
      </asset>
    </ressources>
    <timeline properties='properties;' metadatas='metadatas, duration=(guint64)22000000000;'>
      <track caps='video/x-raw(ANY)' track-type='4' track-id='0' properties='properties, message-forward=(boolean)true, restriction-caps=(string)&quot;video/x-raw\(ANY\)\,\ width\=\(int\)1920\,\ height\=\(int\)1080\,\ framerate\=\(fraction\)30/1&quot;, id=(string)5a1b78402117fb5146c8f9defb3bae08;' metadatas='metadatas;'/>
      <track caps='audio/x-raw(ANY)' track-type='2' track-id='1' properties='properties, message-forward=(boolean)true, restriction-caps=(string)&quot;audio/x-raw\(ANY\)\,\ rate\=\(int\)48000\,\ channels\=\(int\)2&quot;, id=(string)4933fc6d0365bb5f40e62c37d7622a57;' metadatas='metadatas;'/>
      <layer priority='0' properties='properties;' metadatas='metadatas, volume=(float)1, video::name=(string)credits;'>
        <clip id='0' asset-id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/2.png' type-name='GESUriClip' layer-priority='0' track-types='4' start='16000000000' duration='3000000000' inpoint='0' rate='0' properties='properties, name=(string)uriclip0, is-image=(boolean)true;' metadatas='metadatas;'>
          <source track-id='0' properties='properties, track-type=(int)4, has-internal-source=(boolean)true;' metadatas='metadatas;'  children-properties='properties, GstFramePositioner::alpha=(double)1, GstFramePositioner::height=(int)1080, GstFramePositioner::operator=(int)1, GstFramePositioner::posx=(int)0, GstFramePositioner::posy=(int)0, GstVideoDirection::video-direction=(int)8, GstFramePositioner::width=(int)1920;'>
          </source>
        </clip>
        <clip id='1' asset-id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/3.png' type-name='GESUriClip' layer-priority='0' track-types='4' start='19000000000' duration='3000000000' inpoint='0' rate='0' properties='properties, name=(string)uriclip1, is-image=(boolean)true;' metadatas='metadatas;'>
          <source track-id='0' properties='properties, track-type=(int)4, has-internal-source=(boolean)true;' metadatas='metadatas;'  children-properties='properties, GstFramePositioner::alpha=(double)1, GstFramePositioner::height=(int)1079, GstFramePositioner::operator=(int)1, GstFramePositioner::posx=(int)0, GstFramePositioner::posy=(int)0, GstVideoDirection::video-direction=(int)8, GstFramePositioner::width=(int)1920;'>
          </source>
        </clip>
      </layer>
      <layer priority='1' properties='properties;' metadatas='metadatas, volume=(float)1, video::name=(string)Camera;'>
        <clip id='2' asset-id='file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/video/webcams.webm' type-name='GESUriClip' layer-priority='1' track-types='6' start='6000000000' duration='10000000000' inpoint='3667000000000' rate='0' properties='properties, name=(string)uriclip2;' metadatas='metadatas;'>
          <source track-id='1' properties='properties, track-type=(int)2, has-internal-source=(boolean)true;' metadatas='metadatas;'  children-properties='properties, GstVolume::mute=(boolean)false, GstVolume::volume=(double)1;'>
          </source>
          <source track-id='0' properties='properties, track-type=(int)4, has-internal-source=(boolean)true;' metadatas='metadatas;'  children-properties='properties, GstFramePositioner::alpha=(double)1, GstFramePositioner::height=(int)270, GstFramePositioner::operator=(int)1, GstFramePositioner::posx=(int)1440, GstFramePositioner::posy=(int)0, GstVideoDirection::video-direction=(int)8, GstFramePositioner::width=(int)480;'>
          </source>
        </clip>
      </layer>
      <layer priority='2' properties='properties;' metadatas='metadatas, volume=(float)1, video::name=(string)Slides;'>
        <clip id='3' asset-id='file:///home/jmlich/Desktop/openalt2021-zaznamy/var/bigbluebutton/published/presentation/1ce47f2ad852b72e20b952dd7859c6730861fd14-1636267030659/presentation/982c4b42cb1dcbd7d057f2ceff059c81316da45e-1636275148307/slide-1.png' type-name='GESUriClip' layer-priority='2' track-types='4' start='6000000000' duration='10000000000' inpoint='0' rate='0' properties='properties, name=(string)uriclip3, is-image=(boolean)true;' metadatas='metadatas;'>
          <source track-id='0' properties='properties, track-type=(int)4, has-internal-source=(boolean)true;' metadatas='metadatas;'  children-properties='properties, GstFramePositioner::alpha=(double)1, GstFramePositioner::height=(int)811, GstFramePositioner::operator=(int)1, GstFramePositioner::posx=(int)0, GstFramePositioner::posy=(int)0, GstVideoDirection::video-direction=(int)8, GstFramePositioner::width=(int)1440;'>
          </source>
        </clip>
      </layer>
      <layer priority='3' properties='properties;' metadatas='metadatas, volume=(float)1, video::name=(string)Deskshare;'>
      </layer>
      <layer priority='4' properties='properties;' metadatas='metadatas, volume=(float)1, video::name=(string)Backdrop;'>
        <clip id='4' asset-id='file:///home/jmlich/workspace/openalt2021/bbb-batch-render/output/ne-1-10-00-petr-krcmar-moderni.png' type-name='GESUriClip' layer-priority='4' track-types='4' start='6000000000' duration='10000000000' inpoint='0' rate='0' properties='properties, name=(string)uriclip4, is-image=(boolean)true;' metadatas='metadatas;'>
          <source track-id='0' properties='properties, track-type=(int)4, has-internal-source=(boolean)true;' metadatas='metadatas;'  children-properties='properties, GstFramePositioner::alpha=(double)1, GstFramePositioner::height=(int)1080, GstFramePositioner::operator=(int)1, GstFramePositioner::posx=(int)0, GstFramePositioner::posy=(int)0, GstVideoDirection::video-direction=(int)8, GstFramePositioner::width=(int)1920;'>
          </source>
        </clip>
      </layer>
      <groups>
      </groups>
    </timeline>
  </project>
</ges>
```

pitivi ends with an backtrace
```
$ pitivi ne-1-10-00-petr-krcmar-moderni.xges 

(pitivi:96404): GStreamer-CRITICAL **: 16:16:10.295: gst_value_set_fraction_range: assertion 'gst_util_fraction_compare (start->data[0].v_int, start->data[1].v_int, end->data[0].v_int, end->data[1].v_int) < 0' failed
TypeError: 'float' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/pitivi/application.py", line 219, in do_open
    self.project_manager.load_project(quote_uri(project_file.get_uri()))
  File "/usr/lib64/python3.10/site-packages/pitivi/project.py", line 257, in load_project
    project = Project(self.app, uri=uri, scenario=scenario)
  File "/usr/lib64/python3.10/site-packages/pitivi/project.py", line 729, in __init__
    res = self._ensure_video_restrictions()
  File "/usr/lib64/python3.10/site-packages/pitivi/project.py", line 2097, in _ensure_video_restrictions
    return self._ensure_restrictions(profile, defaults, ref_restrictions, prev_vals)
  File "/usr/lib64/python3.10/site-packages/pitivi/project.py", line 2067, in _ensure_restrictions
    restriction = fixate_caps_with_default_values(encoder_sinkcaps,
  File "/usr/lib64/python3.10/site-packages/pitivi/utils/misc.py", line 377, in fixate_caps_with_default_values
    value = intersect(struct_val, default_val)
  File "/usr/lib64/python3.10/site-packages/pitivi/utils/misc.py", line 303, in intersect
    structure = Gst.Structure('t', t=v1).intersect(Gst.Structure('t', t=v2))
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gst.py", line 286, in __new__
    struct[k] = v
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gst.py", line 310, in __setitem__
    return self.set_value(key, value)
SystemError: gi.FunctionInfo(set_value) returned a result with an exception set
```

**Comment by jmlich** [comment]
It seems there is some issue with PyGObject

https://gitlab.gnome.org/GNOME/pitivi/-/issues/2589

**Comment by jmlich** [comment]
This should solve part of problem
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1358
